name: Make Debian package

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build scripts
      run: sudo apt-get install -y build-essential debhelper devscripts

    - name: Build
      working-directory: ${{github.workspace}}
      run: ./makedeb.sh
