name: Make Debian package

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build scripts
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper devscripts

    - name: Build
      working-directory: ${{github.workspace}}
      run: ./makedeb.sh

    - name: Archive built package
      uses: actions/upload-artifact@v4
      with:
        name: deb-pkg
        path: ${{github.workspace}}/build/*.deb
